scss_files: "app/assets/stylesheets/**"
exclude:
  - "app/assets/stylesheets/application.scss"
  - "vendor/assets/**"
linters:
  VendorPrefix:
    enabled: false
PlaceholderInExtend:
  enabled: false
